export const mockStations = [
  {
    id: "1",
    name: "Tata Power EV Station",
    address: "MG Road, Bengaluru",
    latitude: 12.9716,
    longitude: 77.5946,
    status: "available",
    available_slots: 3,
    total_slots: 4,
    power_output_kw: 50,
    price_per_kwh: 12,
    rating: 4.5,
    connector_type: "CCS2",
    operating_hours: "24/7",
  },
  {
    id: "2",
    name: "EESL Charging Hub",
    address: "Koramangala, Bengaluru",
    latitude: 12.9352,
    longitude: 77.6245,
    status: "low",
    available_slots: 1,
    total_slots: 6,
    power_output_kw: 60,
    price_per_kwh: 14,
    rating: 4.2,
    connector_type: "Type 2",
    operating_hours: "6AM - 11PM",
  },
  {
    id: "3",
    name: "ChargeZone Fast",
    address: "Whitefield, Bengaluru",
    latitude: 12.9698,
    longitude: 77.7499,
    status: "busy",
    available_slots: 0,
    total_slots: 4,
    power_output_kw: 120,
    price_per_kwh: 18,
    rating: 4.8,
    connector_type: "CCS2",
    operating_hours: "24/7",
  },
  {
    id: "4",
    name: "Ather Grid Point",
    address: "Indiranagar, Bengaluru",
    latitude: 12.9784,
    longitude: 77.6408,
    status: "available",
    available_slots: 2,
    total_slots: 2,
    power_output_kw: 22,
    price_per_kwh: 8,
    rating: 4.0,
    connector_type: "Type 2",
    operating_hours: "24/7",
  },
  {
    id: "5",
    name: "Fortum Charge Hub",
    address: "JP Nagar, Bengaluru",
    latitude: 12.9063,
    longitude: 77.5857,
    status: "offline",
    available_slots: 0,
    total_slots: 8,
    power_output_kw: 150,
    price_per_kwh: 20,
    rating: 3.9,
    connector_type: "CHAdeMO",
    operating_hours: "Under Maintenance",
  },
  {
    id: "6",
    name: "Statiq Power Station",
    address: "Electronic City, Bengaluru",
    latitude: 12.8440,
    longitude: 77.6568,
    status: "available",
    available_slots: 5,
    total_slots: 6,
    power_output_kw: 75,
    price_per_kwh: 15,
    rating: 4.6,
    connector_type: "CCS2",
    operating_hours: "24/7",
  },
];
